import { Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { UserStore } from '../../stores/user.store';
import { form, submit } from '@angular/forms/signals';
import { linkedSignal } from '@angular/core';
import { FieldDef, toSchema } from './form-utils';
import { DynamicFormComponent } from './dynamic-form/dynamic-form';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-user-create',
  template: `
    <div class="p-6">
      <h1 class="text-2xl font-bold mb-4">Create New User</h1>

      <!-- User create form -->
      <form (ngSubmit)="onSubmit()" class="max-w-md">
        <app-dynamic-form [metaInfo]="meta" [dynamicForm]="dynamicForm" />

        <div class="flex items-center justify-between">
          <button
            type="button"
            (click)="onCancel()"
            class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          >
            Cancel
          </button>
          <button
            type="submit"
            [disabled]="dynamicForm().invalid()"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            [class.opacity-50]="dynamicForm().invalid()"
            [class.cursor-not-allowed]="dynamicForm().invalid()"
          >
            Create User
          </button>
        </div>
      </form>

      <!-- Error message -->
      @if (errorMessage()) {
      <div class="mt-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
        {{ errorMessage() }}
      </div>
      }
    </div>
  `,
  standalone: true,
  imports: [DynamicFormComponent, FormsModule],
})
export class UserCreateComponent {
  readonly userStore = inject(UserStore);
  readonly router = inject(Router);

  // Define metadata for User entity fields
  meta: FieldDef[] = [
    {
      name: 'name',
      label: 'Name',
      required: true,
      minLength: 2,
      maxLength: 50,
    },
    {
      name: 'email',
      label: 'Email',
      required: true,
      type: 'email',
    },
    {
      name: 'category',
      label: 'Category',
      required: true,
      type: 'select',
      options: [
        { value: 'Admin', label: 'Admin' },
        { value: 'User', label: 'User' },
        { value: 'Moderator', label: 'Moderator' },
      ],
    },
  ];

  // Create a linked signal for the new user data
  user = linkedSignal<any>(() => ({
    name: '',
    email: '',
    category: 'User',
  }));

  // Create the dynamic form
  dynamicForm = form(this.user, toSchema(this.meta));

  errorMessage = signal('');

  onSubmit() {
    submit(this.dynamicForm, async () => {
      const userData = this.user();

      try {
        // Remove id from userData as it will be generated by the server
        const { id, ...newUser } = userData;

        await this.userStore.createUser(newUser);
        this.router.navigate(['/users']);
        return null; // No validation errors
      } catch (error) {
        this.errorMessage.set('Failed to create user');
        console.error('Error creating user:', error);
        // Return a validation error to display in the form
        return {
          kind: 'submission_error',
          message: 'Failed to create user',
        };
      }
    });
  }

  onCancel() {
    this.router.navigate(['/users']);
  }
}
